[project]
name = "nox_agent"
version = "0.7.1"
description = "Agente personal y de desarrollo local."
requires-python = "==3.14.6"

[[tool.cxfreeze.executables]]
script = "src/nox_agent/__main__.py"
base = "console"
target_name = "nox"

[tool.cxfreeze.build_exe]
include_path = ["src"]
include_msvcr = true

[tool.cxfreeze.bdist_msi]
add_to_path = true
all_users = false
initial_target_dir = '[LocalAppDataFolder]Programs\Nox'
output_name = "Nox-0.7.1-windows-x64.msi"
product_name = "Nox"
product_version = "0.7.1"
upgrade_code = "{4BDE50F9-A36C-4E4F-B614-33BFC6BE9E04}"
